---
title: "Assignment 3"
author: "Fiona Price"
date: "2024-10-22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#Load in packages
library(here)
library(tidyr)
library(lubridate)
library(dplyr)

#Load in data
RDU_precip <- read.csv(file = 
    here("./Assignment3/Data Raw/RDU_precip_daily_cm_1942_to_2020-8-10.csv"),
    stringsAsFactors = TRUE)
#Convert class of date column
RDU_precip$DATE <- as.Date(RDU_precip$DATE, format = "%Y-%m-%d")
#Add columns for months and years and remove first 5 columns (because they are
#the same for all the data)
RDU_precip_clean <- RDU_precip %>% 
  mutate(year = year(DATE)) %>% 
  mutate(month = month(DATE)) %>% 
  select(DATE, PRCP, SNOW, SNWD, year, month) %>% 
  filter(PRCP > 0)

class(RDU_precip_clean$PRCP)

```

```{r calculating return period}
#Calculate return period using Weibull
 RDU_rp <-  RDU_precip_clean %>% 
  mutate(rank = rank(-PRCP,
                        ties.method = "max")) %>% 
  mutate(number_events = 8669) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#2-year event is 5.3 inches
#5-year event is 16.3 inches
#So, average rainfall intensity in in/hr for 2-year event is 0.22 in/hr 
#Average rainfall intensity in in/hr for 5-year event is 1.14 in/hr 
```


